import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# ==========================================
# STEP 1: STREAMLIT ENVIRONMENT INITIALIZATION
# ==========================================
st.set_page_config(page_title="Reversal Engine Fixed", layout="wide")
st.title("📊 Custom Reversal Engine Dashboard")
st.write("Strict Time Window Lock: **Jan 2025 - Dec 2026**")

# ==========================================
# STEP 2: SIDEBAR METRIC CONTROLS
# ==========================================
st.sidebar.header("🎛️ Parameters Setup")
ticker = st.sidebar.text_input("Ticker Name (e.g., BTC-USD, RELIANCE.NS)", value="BTC-USD")
delta_lookback = st.sidebar.number_input("Delta Lookback (Column C)", min_value=1, value=14)
long_roc = st.sidebar.number_input("Coppock Long ROC", min_value=1, value=14)
short_roc = st.sidebar.number_input("Coppock Short ROC", min_value=1, value=11)
wma_smoothing = st.sidebar.number_input("Coppock WMA Smoothing", min_value=1, value=10)

# ==========================================
# STEP 3: FLATTENED DATA INGESTION PIPELINE
# ==========================================
@st.cache_data
def fetch_clean_data(symbol):
    # Fetching multi-year raw data block to prevent math cutoff truncation
    raw_download = yf.download(tickers=symbol, interval="1h", period="max")
    
    # CRITICAL FIX: Flatten multi-level index if generated by yfinance
    if isinstance(raw_download.columns, pd.MultiIndex):
        raw_download.columns = raw_download.columns.get_level_values(0)
        
    return raw_download

try:
    # Loading global data series
    raw_df = fetch_clean_data(ticker)
    
    if raw_df.empty:
        st.error("❌ Data download fail ho gaya. Kripya correct Ticker format use karein.")
    else:
        # Creating an active deep copy to process data metrics smoothly
        working_df = raw_df.copy()

        # ==========================================
        # STEP 4: COLUMN C (DELTA PULSE) PROCESSING
        # ==========================================
        working_df['ColumnC_Delta'] = working_df['Close'] - working_df['Close'].shift(int(delta_lookback))

        # ==========================================
        # STEP 5: COPPOCK VECTOR MATRIX CALCULATION
        # ==========================================
        working_df['ROC_Long'] = ((working_df['Close'] - working_df['Close'].shift(int(long_roc))) / working_df['Close'].shift(int(long_roc))) * 100
        working_df['ROC_Short'] = ((working_df['Close'] - working_df['Close'].shift(int(short_roc))) / working_df['Close'].shift(int(short_roc))) * 100
        working_df['RawMatrixSum'] = working_df['ROC_Long'] + working_df['ROC_Short']
        
        # WMA Array Matrix alignment
        weights = np.arange(1, int(wma_smoothing) + 1)
        working_df['CoppockCurve'] = working_df['RawMatrixSum'].rolling(int(wma_smoothing)).apply(
            lambda x: np.dot(x, weights) / weights.sum(), raw=True
        )

        # ==========================================
        # STEP 6: CROSSOVER CONVERGENCE DETECTION
        # ==========================================
        working_df['Coppock_Prev'] = working_df['CoppockCurve'].shift(1)
        working_df['Bullish_Hint'] = (working_df['ColumnC_Delta'] > 0) & (working_df['CoppockCurve'] > 0) & (working_df['Coppock_Prev'] <= 0)
        working_df['Bearish_Hint'] = (working_df['ColumnC_Delta'] < 0) & (working_df['CoppockCurve'] < 0) & (working_df['Coppock_Prev'] >= 0)

        # ==========================================
        # STEP 7: STAGE-GATE 2-YEAR DATA FREEZE LOCK
        # ==========================================
        start_date = pd.Timestamp("2025-01-01 00:00:00")
        end_date = pd.Timestamp("2026-12-31 23:59:59")
        
        # Final safe dataframe sequence generation
        df = working_df[(working_df.index >= start_date) & (working_df.index <= end_date)].copy()

        # ==========================================
        # STEP 8: INTERACTIVE UI RENDERING
        # ==========================================
        if df.empty:
            st.warning("⚠️ Is specific freeze period (2025-2026) me selected asset ka data points matrix empty hai.")
        else:
            # Main Candlestick Chart Execution
            fig = go.Figure()
            fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name="Price Engine"))
            
            # Plotting Long Points
            longs = df[df['Bullish_Hint']]
            fig.add_trace(go.Scatter(x=longs.index, y=longs['Low'] * 0.995, mode='markers', marker=dict(symbol='triangle-up', size=12, color='#00FF00'), name='LONG ENTRY'))
            
            # Plotting Short Points
            shorts = df[df['Bearish_Hint']]
            fig.add_trace(go.Scatter(x=shorts.index, y=shorts['High'] * 1.005, mode='markers', marker=dict(symbol='triangle-down', size=12, color='#FF0000'), name='SHORT ENTRY'))
            
            fig.update_layout(height=600, template="plotly_dark", xaxis_rangeslider_visible=False)
            st.plotly_chart(fig, use_container_width=True)
            
            # Outcome Data Logs Matrix table display
            st.subheader("📋 Verified Engine Logs (All Possible Outcome Dates)")
            signals = df[df['Bullish_Hint'] | df['Bearish_Hint']].copy()
            if not signals.empty:
                signals['Signal_Type'] = np.where(signals['Bullish_Hint'], '🟢 BUY / LONG', '🔴 SELL / SHORT')
                st.dataframe(signals[['Close', 'ColumnC_Delta', 'CoppockCurve', 'Signal_Type']].tail(30), use_container_width=True)
            else:
                st.info("No active signals captured in this 2-year freeze iteration with current parameter sets.")

except Exception as global_error:
    st.error(f"⚠️ High-Level Execution Halt: {global_error}")
